version: "3"

services:
  mero-node-app:
    build: 
      context: . 
      args:
        NODE_ENV: development

    volumes:
      - ./:/app 
      - /app/node_modules 
    
    environment:
      - NOVE_ENV=development
    
    command: npm run dev